#!/bin/bash

# Exit on error
set -e

PSQL="psql -U $POSTGRES_USER -d $POSTGRES_DB -c"

${PSQL} "CREATE EXTENSION IF NOT EXISTS postgis;"
${PSQL} "CREATE EXTENSION IF NOT EXISTS postgis_raster;"
${PSQL} "CREATE EXTENSION IF NOT EXISTS pgcrypto;"

${PSQL} "CREATE SCHEMA IF NOT EXISTS raw;"
${PSQL} "CREATE SCHEMA IF NOT EXISTS staging;"
${PSQL} "CREATE SCHEMA IF NOT EXISTS mart;"

# ${PSQL} "GRANT ALL ON SCHEMA raw, staging, mart TO CURRENT_USER;"