name: extractor-openmeteo

services:
  extractor-openmeteo:
    build:
      context: ${PWD}/services/extractor-openmeteo
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=$DATABASE_URL
    depends_on:
      postgres:
        condition: 'service_healthy'
    networks:
      - backend
    restart: unless-stopped