name: extractor-openmeteo

services:
  extractor-openmeteo:
    build:
      context: ${PWD}/services/extractor-openmeteo
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      postgres:
        condition: 'service_healthy'
    networks:
      - backend
    restart: unless-stopped