name: api

services:
  api:
    build:
      context: ${PWD}/services/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ${PWD}/services/api/src:/app/src
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - MINIO_ENDPOINT=$MINIO_ENDPOINT
      - MINIO_ROOT_USER=$MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
    depends_on:
      postgres:
        condition: 'service_healthy'
      minio:
        condition: 'service_healthy'
    networks:
      - backend